db:
  container_name: pokemones_db
  image: mysql
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  environment: 
    - MYSQL_USER=root
    - MYSQL_ROOT_PASSWORD=toor
    - MYSQL_DATABASE=bruteforce
  ports:
    - 3306
  volumes:
    - ./mysql:/docker-entrypoint-initdb.d
php:
  container_name: pokemones
  build: .
  volumes:
    - ".:/var/www/html/"
  ports:
    - "3000:80"
  environment:
    - PHP_ENV=production
  links:
    - db