db0:
  container_name: brutforce_db
  image: mysql
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  environment: 
    - MYSQL_USER=root
    - MYSQL_ROOT_PASSWORD=toor
    - MYSQL_DATABASE=bruteforce
  ports:
    - 3306
db1:
  container_name: sqli_db
  image: mysql
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  environment: 
    - MYSQL_USER=root
    - MYSQL_ROOT_PASSWORD=toor
    - MYSQL_DATABASE=sqli
php:
  container_name: pokemones
  build: .
  volumes:
    - ".:/var/www/html/"
  ports:
    - "4000:80"
  environment:
    - PHP_ENV=production
  links:
    - db0
    - db1